Repository RealDeviceMap/RealDeviceMap, pull requests merged in 2020-05, with the labels that each got.

#92 Fix and improve Circle Smart Raid Instance
  Sources/RealDeviceMap/Controller/Instance Controllers/AutoInstanceController.swift
  Sources/RealDeviceMap/Controller/Instance Controllers/CircleSmartRaidInstanceController.swift
  Sources/RealDeviceMap/Misc/S2LatLng.swift
  Sources/RealDeviceMap/Web/WebReqeustHandler.swift
  resources/migrations/3.sql
  resources/webroot/index.js.mustache
Labels: backend, bugfix

#94 Fix map no longer loading after api error
  resources/webroot/index.js.mustache
Labels: bugfix, frontend

#93 Update protos to 0.173.2
  Package.swift
  Sources/RealDeviceMap/Modell/Pokestop.swift
  resources/webroot/static/data/de.json
  resources/webroot/static/data/en.json
  resources/webroot/static/data/it.json
Labels: backend, enhancement

#99 Save Table State for Dashboard pages
  resources/webroot/dashboard_accounts.mustache
  resources/webroot/dashboard_assignments.mustache
  resources/webroot/dashboard_devicegroups.mustache
  resources/webroot/dashboard_devices.mustache
  resources/webroot/dashboard_discordrules.mustache
  resources/webroot/dashboard_groups.mustache
  resources/webroot/dashboard_instance_ivqueue.mustache
  resources/webroot/dashboard_instances.mustache
  resources/webroot/dashboard_users.mustache
Labels: backend, enhancement

#100 Trim whitespace from account import
  Sources/RealDeviceMap/Web/WebReqeustHandler.swift
Labels: backend, bugfix

#96 Simple login limiter
  Sources/RealDeviceMap/Controller/AccountController.swift
  Sources/RealDeviceMap/Controller/AssignmentController.swift
  Sources/RealDeviceMap/Controller/DBController.swift
  Sources/RealDeviceMap/Controller/Instance Controllers/AutoInstanceController.swift
  Sources/RealDeviceMap/Controller/Instance Controllers/IVInstanceController.swift
  Sources/RealDeviceMap/Controller/Instance Controllers/InstanceController.swift
  Sources/RealDeviceMap/Misc/main.swift
  Sources/RealDeviceMap/Modell/Device.swift
  Sources/RealDeviceMap/Modell/Pokestop.swift
  Sources/RealDeviceMap/Webhook/WebHookRequestHandler.swift
  docker-compose.yml
Labels: backend, enhancement, minor

#104 Store Dashboard TableState Indefinitely
  resources/webroot/dashboard_accounts.mustache
  resources/webroot/dashboard_assignments.mustache
  resources/webroot/dashboard_devicegroups.mustache
  resources/webroot/dashboard_devices.mustache
  resources/webroot/dashboard_discordrules.mustache
  resources/webroot/dashboard_groups.mustache
  resources/webroot/dashboard_instance_ivqueue.mustache
  resources/webroot/dashboard_instances.mustache
  resources/webroot/dashboard_users.mustache
Labels: backend, bugfix, patch

#103 Use X-Forwarded-For Header for Login limiting and devices page host
  Sources/RealDeviceMap/Webhook/WebHookRequestHandler.swift
Labels: backend, bugfix, patch

#105 Show Version on Dashboard (/dashboard)
  .github/docker/Dockerfile-localbuild-debug
  .github/docker/Dockerfile-localbuild-release
  .gitignore
  .gitref
  .gitsha
  Dockerfile-debug
  Dockerfile-release
  Sources/RealDeviceMap/Misc/VersionManager.swift
  Sources/RealDeviceMap/Misc/main.swift
  Sources/RealDeviceMap/Web/WebReqeustHandler.swift
  resources/webroot/dashboard.mustache
Labels: backend, enhancement, minor

#109 Fixes Incorrect Spawnpoint Longitude
  Sources/RealDeviceMap/Modell/Pokemon.swift
Labels: backend, bugfix, patch

#112 Fix Missing Localization for Quest 35
  resources/webroot/static/data/de.json
  resources/webroot/static/data/en.json
Labels: bugfix, frontend, patch

#110 Fix S2Cell WebHook Weather Event Naming
  Sources/RealDeviceMap/Modell/Weather.swift
Labels: backend, bugfix, patch

#108 Update Protos to 0.175.0
  Package.swift
  Sources/RealDeviceMap/Modell/Pokestop.swift
  resources/webroot/index.js.mustache
  resources/webroot/static/data/de.json
  resources/webroot/static/data/en.json
  resources/webroot/static/data/it.json
Labels: backend, enhancement, minor

#106 IPv6 Support for Login-Limitter and for Device Host
  Sources/RealDeviceMap/API/ApiRequestHandler.swift
  Sources/RealDeviceMap/Misc/HTTPRequest.swift
  Sources/RealDeviceMap/Web/WebReqeustHandler.swift
  Sources/RealDeviceMap/Webhook/WebHookRequestHandler.swift
Labels: backend, bugfix, patch

#83 Smarter getNewAccount per instance
  Sources/RealDeviceMap/Controller/DBController.swift
  Sources/RealDeviceMap/Controller/Instance Controllers/AutoInstanceController.swift
  Sources/RealDeviceMap/Controller/Instance Controllers/CircleInstanceController.swift
  Sources/RealDeviceMap/Controller/Instance Controllers/CircleSmartRaidInstanceController.swift
  Sources/RealDeviceMap/Controller/Instance Controllers/IVInstanceController.swift
  Sources/RealDeviceMap/Controller/Instance Controllers/InstanceController.swift
  Sources/RealDeviceMap/Controller/Instance Controllers/LevelingInstanceController.swift
  Sources/RealDeviceMap/Misc/Cooldown.swift
  Sources/RealDeviceMap/Misc/main.swift
  Sources/RealDeviceMap/Modell/Account.swift
  Sources/RealDeviceMap/Web/WebReqeustHandler.swift
  Sources/RealDeviceMap/Webhook/WebHookRequestHandler.swift
  resources/migrations/62.sql
Labels: backend, bugfix, db-migration, enhancement, minor

#118 Fix Account Assignment Collisions
  Sources/RealDeviceMap/Controller/Instance Controllers/AutoInstanceController.swift
  Sources/RealDeviceMap/Controller/Instance Controllers/CircleInstanceController.swift
  Sources/RealDeviceMap/Controller/Instance Controllers/CircleSmartRaidInstanceController.swift
  Sources/RealDeviceMap/Controller/Instance Controllers/IVInstanceController.swift
  Sources/RealDeviceMap/Controller/Instance Controllers/InstanceController.swift
  Sources/RealDeviceMap/Controller/Instance Controllers/LevelingInstanceController.swift
  Sources/RealDeviceMap/Modell/Account.swift
  Sources/RealDeviceMap/Webhook/WebHookRequestHandler.swift
Labels: backend, bugfix, patch

#121 Improved Device Logging
  Sources/RealDeviceMap/Webhook/WebHookRequestHandler.swift
Labels: backend, bugfix, patch

#122 Fix Questing Login Loops
  Sources/RealDeviceMap/Controller/Instance Controllers/AutoInstanceController.swift
  Sources/RealDeviceMap/Misc/Cooldown.swift
  Sources/RealDeviceMap/Webhook/WebHookRequestHandler.swift
Labels: backend, bugfix, patch
