Repository RealDeviceMap/RealDeviceMap, pull requests merged in 2020-07, with the labels that each got.

#113 Performance Improvements
  Sources/RealDeviceMap/API/ApiRequestHandler.swift
  Sources/RealDeviceMap/Controller/Instance Controllers/AutoInstanceController.swift
  Sources/RealDeviceMap/Misc/VersionManager.swift
  Sources/RealDeviceMap/Modell/Gym.swift
  Sources/RealDeviceMap/Modell/Instance.swift
  Sources/RealDeviceMap/Modell/Pokemon.swift
  Sources/RealDeviceMap/Modell/Pokestop.swift
  Sources/RealDeviceMap/Web/WebReqeustHandler.swift
Labels: backend, enhancement, minor

#129 Add Galarian form
  resources/webroot/static/data/de.json
  resources/webroot/static/data/en.json
Labels: bugfix, frontend, patch

#147 add pikachu forms and new moves
  resources/webroot/static/data/en.json
  resources/webroot/static/data/pokemon.json
Labels: bugfix, frontend, patch

#130 Fix cols for gyms without active raid
  resources/webroot/index.js.mustache
Labels: bugfix, frontend, patch

#115 Simple Pokestop Clustering for Questing
  Sources/RealDeviceMap/Controller/Instance Controllers/AutoInstanceController.swift
  Sources/RealDeviceMap/Controller/Instance Controllers/LevelingInstanceController.swift
Labels: backend, enhancement, minor

#125 Fix Duplicated WebHook Events
  Sources/RealDeviceMap/Modell/Account.swift
  Sources/RealDeviceMap/Modell/Gym.swift
  Sources/RealDeviceMap/Modell/Pokemon.swift
  Sources/RealDeviceMap/Modell/Pokestop.swift
  Sources/RealDeviceMap/Modell/Weather.swift
  Sources/RealDeviceMap/Webhook/WebHookRequestHandler.swift
Labels: backend, bugfix, patch

#141 Fix Login Loop Race-Condition in Questing Instance
  Sources/RealDeviceMap/Controller/Instance Controllers/AutoInstanceController.swift
  Sources/RealDeviceMap/Webhook/WebHookRequestHandler.swift
Labels: backend, bugfix, patch

#149 Fix Weather not saving
  Sources/RealDeviceMap/Modell/Weather.swift
Labels: backend, bugfix, patch

#150 Fixxed wrong german translations (typos)
  resources/webroot/static/data/de.json
Labels: bugfix, frontend, patch

#120 PVP Stats
  .github/docker/Dockerfile-localbuild-base
  .github/docker/Dockerfile-localbuild-debug
  .github/docker/Dockerfile-localbuild-release
  .github/workflows/swift.yml
  .gitignore
  .swift-version
  .swiftlint.yml
  Dockerfile-debug
  Dockerfile-release
  Package.swift
  Sources/RealDeviceMap/API/ApiRequestHandler.swift
  Sources/RealDeviceMap/Controller/InstanceControllers/AutoInstanceController.swift
  Sources/RealDeviceMap/Controller/InstanceControllers/CircleInstanceController.swift
  Sources/RealDeviceMap/Controller/InstanceControllers/CircleSmartRaidInstanceController.swift
  Sources/RealDeviceMap/Controller/InstanceControllers/IVInstanceController.swift
  Sources/RealDeviceMap/Controller/InstanceControllers/InstanceController.swift
  Sources/RealDeviceMap/Controller/InstanceControllers/LevelingInstanceController.swift
  Sources/RealDeviceMap/Controller/WebHookController.swift
  Sources/RealDeviceMap/Misc/ImageGenerator.swift
  Sources/RealDeviceMap/Misc/PVPStatsManager.swift
  Sources/RealDeviceMap/Misc/main.swift
  Sources/RealDeviceMap/Modell/Coord.swift
  Sources/RealDeviceMap/Modell/Device.swift
  Sources/RealDeviceMap/Modell/DeviceGroup.swift
  Sources/RealDeviceMap/Modell/Gym.swift
  Sources/RealDeviceMap/Modell/Instance.swift
  Sources/RealDeviceMap/Modell/Pokemon.swift
  Sources/RealDeviceMap/Modell/Pokestop.swift
  Sources/RealDeviceMap/Web/WebReqeustHandler.swift
  resources/migrations/63.sql
  resources/webroot/index.js.mustache
Labels: backend, db-migration, enhancement, frontend, minor
