Repository RealDeviceMap/RealDeviceMap, pull requests merged in 2021-06, with the labels that each got.

#208 Cell Pokemon Support
  Sources/RealDeviceMap/API/ApiRequestHandler.swift
  Sources/RealDeviceMap/Controller/InstanceControllers/IVInstanceController.swift
  Sources/RealDeviceMap/Misc/ImageGenerator.swift
  Sources/RealDeviceMap/Misc/main.swift
  Sources/RealDeviceMap/Modell/Pokemon.swift
  docker-compose.yml
  resources/webroot/index.js.mustache
  resources/webroot/static/data/de.json
  resources/webroot/static/data/en.json
Labels: backend, enhancement, frontend, minor

#221 Update docker-compose.yml
  docker-compose.yml
Labels: documentation

#220 fix: quest translations added
  resources/webroot/index.js.mustache
  resources/webroot/static/data/de.json
  resources/webroot/static/data/en.json
Labels: bugfix, frontend, patch
