Repository RealDeviceMap/RealDeviceMap, pull requests merged in 2022-03, with the labels that each got.

#308 fix static file handler and Charts in Stats
  Sources/RealDeviceMapLib/Web/WebStaticRequestHandler.swift
  resources/webroot/header-head.mustache
  resources/webroot/static/js/utils.js
Labels: backend, frontend, bugfix

#285 Local Uicon support / On-Demand Image Generation
  .gitignore
  .swiftlint.yml
  Sources/RealDeviceMapLib/API/ApiRequestHandler.swift
  Sources/RealDeviceMapLib/ImageAPI/ImageAPIRoutes.swift
  Sources/RealDeviceMapLib/ImageAPI/ImageApiRequestHandler.swift
  Sources/RealDeviceMapLib/Misc/File.swift
  Sources/RealDeviceMapLib/Misc/ImageGenerator.swift
  Sources/RealDeviceMapLib/Misc/ImageManager.swift
  Sources/RealDeviceMapLib/Misc/RewardType.swift
  Sources/RealDeviceMapLib/Misc/Shell.swift
  Sources/RealDeviceMapLib/Misc/String.swift
  Sources/RealDeviceMapLib/Misc/UInt8.swift
  Sources/RealDeviceMapLib/Modell/Account.swift
  Sources/RealDeviceMapLib/Modell/Pokestop.swift
  Sources/RealDeviceMapLib/Modell/Stats.swift
  Sources/RealDeviceMapLib/Web/WebRequestHandler.swift
  Sources/RealDeviceMapLib/Web/WebServer.swift
  Sources/RealDeviceMapLib/setup.swift
  resources/webroot/dashboard_instance_add.mustache
  resources/webroot/dashboard_instance_edit.mustache
  resources/webroot/dashboard_settings.mustache
  resources/webroot/header-head.mustache
  resources/webroot/index.js.mustache
  resources/webroot/index.mustache
  resources/webroot/static/data/de.json
  resources/webroot/static/data/en.json
  resources/webroot/static/data/pokemon.json
  resources/webroot/static/js/i18n.min.js
  resources/webroot/static/misc/maps_apple.png
  resources/webroot/static/misc/maps_google.png
  resources/webroot/static/misc/maps_waze.png
  resources/webroot/static/misc/timer.png
  resources/webroot/stats.mustache
Labels: enhancement, backend, frontend

#317 Ability to save `spawnpoint.last_seen`
  Sources/RealDeviceMapLib/Modell/Pokemon.swift
  Sources/RealDeviceMapLib/Modell/SpawnPoint.swift
  Sources/RealDeviceMapLib/setup.swift
  docker-compose.yml
  resources/migrations/79.sql
Labels: backend, db-migration

#320 reload instance when quests are cleared with re-quest
  Sources/RealDeviceMapLib/Controller/AssignmentController.swift
Labels: backend

#316 PVP Improvements (level caps, league filter, little league, ...)
  .swiftlint.yml
  Sources/RealDeviceMapLib/Misc/PVPStatsManager.swift
  Sources/RealDeviceMapLib/Modell/Gym.swift
  Sources/RealDeviceMapLib/Modell/Pokemon.swift
  Sources/RealDeviceMapLib/setup.swift
  docker-compose.yml
  resources/migrations/80.sql
  resources/webroot/index.js.mustache
Labels: enhancement, backend, frontend, db-migration, major
